### PR TITLE
Prospectusupdate

### PR DESCRIPTION
**Pull request by MasonWang025**
prospectus pdf is updated

### CODE REVIEW

**Comment by MasonWang025** [comment]
well life sucks doesn't it

**Comment by MasonWang025** [comment]
all checks failed and idek what

**Comment by SwiftWinds** [comment]
maybe try googling this error:

```
Error downloading object: TogaHacks Sponsorship Prospectus.pdf (d0fd043): Smudge error: Error downloading TogaHacks Sponsorship Prospectus.pdf (d0fd043a2493e93681a87990e0311eac4c80f8068850fd8c607caf651392d8a4): batch request: missing protocol: ""
```

or reading git lfs logs?

**Comment by MasonWang025** [comment]
its git lfs problem

**Comment by SwiftWinds** [comment]
Added in https://github.com/Toga-Hacks-I/Toga-Hacks-Website/pull/35

**Pull request closed without merging**
